import type {
  Achievement,
  AdmissionRequirement,
  BonusRule,
  DailyControl,
  MentorSkill,
  Mission,
  PenaltyRule,
  PracticalExamItem,
  Reward,
  ShiftJournalEntry,
  TraineeSummary,
  TrainingState,
} from "@/types/training";
import { assetPath } from "@/lib/assets";

export const missions: Mission[] = [
  {
    id: "welcome",
    order: 1,
    title: "Добро пожаловать",
    subtitle: "Компания, ценности, культура",
    type: "quiz",
    duration: "5 мин",
    xp: 10,
    stars: 1,
    passScore: 80,
    source: "PDF: Этап 1, день 1",
    goals: ["Понять миссию и ценности", "Узнать правила дисциплины", "Запомнить базовую безопасность"],
    lessonCards: [
      { title: "Компания", body: "Новичок знакомится с историей, миссией, ценностями и корпоративной культурой ресторана." },
      { title: "Дисциплина", body: "График, пунктуальность и правила общения влияют на допуск к следующим этапам." },
      { title: "Безопасность", body: "Стажер должен знать санитарные нормы, служебные зоны и правила поведения на смене." },
    ],
    contentBlocks: [
      {
        id: "welcome-text",
        type: "text",
        title: "Перед стартом",
        body: "Сначала посмотри welcome-материалы: коротко про компанию, базовые правила, дисциплину и то, как будет идти стажировка.",
        bullets: ["Понять миссию и ценности", "Узнать правила дисциплины", "Запомнить базовую безопасность"],
      },
      {
        id: "welcome-video-main",
        type: "video",
        title: "WELCOME ролик",
        description: "Первое знакомство с рестораном и ожиданиями от стажера.",
        duration: "1 мин 59 сек",
        url: assetPath("/training/videos/welcome.mp4"),
      },
      {
        id: "welcome-book-pdf",
        type: "pdf",
        title: "WELCOME BOOK",
        sourceLabel: "WELCOME BOOK. обновленный.pdf",
        fileUrl: assetPath("/training/pdfs/welcome-book.pdf"),
      },
    ],
    quiz: {
      question: "Какой минимальный результат нужен на устном контроле первого дня?",
      options: ["60%", "80%", "100%"],
      answer: 1,
      explanation: "В PDF для первого дня указан устный опрос наставника с минимальным проходным баллом 80%.",
    },
    achievementId: "first-step",
  },
  {
    id: "appearance-standards",
    order: 2,
    title: "Внешний вид",
    subtitle: "Форма и стандарты",
    type: "lesson",
    duration: "4 мин",
    xp: 8,
    stars: 1,
    source: "PDF: стандарты внешнего вида",
    goals: ["Выучить требования к форме", "Понять, что оценивает наставник", "Избежать штрафов за внешний вид"],
    lessonCards: [
      { title: "Форма", body: "Форма должна быть чистой, аккуратной и соответствовать стандарту ресторана." },
      { title: "Оценка", body: "Внешний вид входит в ежедневный чек-лист наставника и оценивается по шкале 1-5." },
    ],
    achievementId: "appearance",
  },
  {
    id: "restaurant-rules",
    order: 3,
    title: "Правила ресторана",
    subtitle: "Структура, зоны, команда",
    type: "lesson",
    duration: "5 мин",
    xp: 10,
    stars: 0,
    source: "PDF: экскурсия и структура ресторана",
    goals: ["Понять структуру ресторана", "Запомнить служебные помещения", "Узнать роли сотрудников"],
    lessonCards: [
      { title: "Схема зала", body: "Стажер должен понимать станции, проходы, гостевые зоны и служебные маршруты." },
      { title: "Команда", body: "Важно знать, кто отвечает за зал, кухню, бар, кассу и помощь новичкам." },
    ],
  },
  {
    id: "sanitary-rules",
    order: 4,
    title: "Санитарные нормы",
    subtitle: "Чистота, безопасность, порядок",
    type: "quiz",
    duration: "6 мин",
    xp: 12,
    stars: 1,
    passScore: 80,
    source: "PDF: техника безопасности и санитарные нормы",
    goals: ["Понять санитарные требования", "Знать стандарты чистоты", "Не допускать грубых нарушений"],
    lessonCards: [
      { title: "Чистота", body: "Стол, станция, посуда и форма должны соответствовать стандарту до контакта с гостем." },
      { title: "Нарушения", body: "За несоблюдение стандартов и плохую дисциплину баллы могут сниматься." },
    ],
    quiz: {
      question: "Что из этого считается нарушением стандарта?",
      options: ["Чистая станция", "Грязный стол после ухода гостя", "Повтор заказа гостю"],
      answer: 1,
      explanation: "Чистота зала и стола входит в ежедневный контроль наставника.",
    },
  },
  {
    id: "day-one-check",
    order: 5,
    title: "Опрос наставника",
    subtitle: "Контроль дня 1",
    type: "mentor",
    duration: "смена",
    xp: 12,
    stars: 1,
    source: "PDF: контроль дня 1",
    goals: ["Ответить на вопросы наставника", "Подтвердить знание правил", "Открыть следующий блок"],
    lessonCards: [
      { title: "Что проверяется", body: "Компания, структура ресторана, форма, дисциплина, безопасность и санитарные нормы." },
      { title: "Результат", body: "После успешного контроля сотрудник получает внутренний балл и доступ к следующему этапу." },
    ],
    requiresMentor: true,
  },
  {
    id: "service-basics",
    order: 6,
    title: "Основы сервиса",
    subtitle: "Этапы обслуживания",
    type: "quiz",
    duration: "7 мин",
    xp: 15,
    stars: 1,
    passScore: 85,
    source: "PDF: Этап 1, день 2",
    goals: ["Выучить этапы сервиса", "Понять подачу меню", "Запомнить последовательность обслуживания"],
    lessonCards: [
      { title: "Последовательность", body: "Приветствие, меню, заказ, уточнение, подача, контроль стола, расчет и прощание." },
      { title: "Контакт", body: "Гость должен чувствовать внимание, спокойствие и готовность помочь." },
    ],
    quiz: {
      question: "Что идет в начале базового сервиса?",
      options: ["Расчет", "Приветствие и подача меню", "Уборка стола"],
      answer: 1,
      explanation: "В PDF отдельно указаны приветствие, подача меню и последовательность обслуживания.",
    },
    achievementId: "service-standard",
  },
  {
    id: "greeting-training",
    order: 7,
    title: "Тренировка приветствия",
    subtitle: "Фразы и первый контакт",
    type: "lesson",
    duration: "5 мин",
    xp: 10,
    stars: 0,
    source: "PDF: практика дня 2",
    goals: ["Отработать приветствие", "Подать меню без паузы", "Начать контакт уверенно"],
    lessonCards: [
      { title: "Фраза приветствия", body: "Фраза должна быть короткой, живой и понятной, без заученного холода." },
      { title: "Темп", body: "Стажер тренирует приветствие и подачу меню до автоматизма." },
    ],
  },
  {
    id: "table-service",
    order: 8,
    title: "Сервировка стола",
    subtitle: "Приборы, чистота, порядок",
    type: "lesson",
    duration: "6 мин",
    xp: 10,
    stars: 0,
    source: "PDF: практика дня 2",
    goals: ["Поставить приборы", "Проверить чистоту", "Не нарушить порядок сервировки"],
    lessonCards: [
      { title: "Приборы", body: "Постановка приборов должна быть аккуратной, быстрой и без лишних касаний." },
      { title: "Контроль", body: "Сервировка связана с чистотой, поэтому наставник оценивает оба навыка вместе." },
    ],
  },
  {
    id: "tray-practice",
    order: 9,
    title: "Поднос",
    subtitle: "Перенос посуды",
    type: "mentor",
    duration: "смена",
    xp: 15,
    stars: 2,
    source: "PDF: работа с подносом",
    goals: ["Переносить посуду безопасно", "Держать темп", "Не мешать движению зала"],
    lessonCards: [
      { title: "Устойчивость", body: "Наставник смотрит уверенность, безопасность движения и аккуратность с посудой." },
      { title: "Практика", body: "Сотрудник отрабатывает поднос, постановку приборов, подачу и уборку." },
    ],
    achievementId: "floor-ready",
    requiresMentor: true,
  },
  {
    id: "service-checklist",
    order: 10,
    title: "Чек-лист сервиса",
    subtitle: "Контроль дня 2",
    type: "mentor",
    duration: "смена",
    xp: 15,
    stars: 1,
    source: "PDF: чек-лист наставника",
    goals: ["Получить оценку по сервису", "Закрыть практику дня 2", "Открыть рейтинг"],
    lessonCards: [
      { title: "Что оценивается", body: "Внешний вид, дисциплина, коммуникация, знание меню, продажи, скорость и чистота." },
      { title: "Результат", body: "После успешного чек-листа открывается мини-игра и первый рейтинг." },
    ],
    requiresMentor: true,
  },
  {
    id: "menu-product",
    order: 11,
    title: "Меню ресторана",
    subtitle: "Блюда и популярные позиции",
    type: "lesson",
    duration: "8 мин",
    xp: 15,
    stars: 0,
    source: "PDF: Этап 1, день 3",
    goals: ["Знать популярные позиции", "Понимать состав блюд", "Работать со стоп-листом"],
    lessonCards: [
      { title: "Меню", body: "Стажер изучает состав блюд, технологии приготовления, популярные позиции и стоп-лист." },
      { title: "Уверенность", body: "Гость доверяет официанту, когда тот объясняет блюдо без угадывания." },
    ],
  },
  {
    id: "allergens",
    order: 12,
    title: "Аллергены",
    subtitle: "Безопасные ответы",
    type: "quiz",
    duration: "6 мин",
    xp: 15,
    stars: 1,
    passScore: 85,
    source: "PDF: аллергены",
    goals: ["Знать базовые аллергены", "Не угадывать состав", "Уточнять безопасно"],
    lessonCards: [
      { title: "Правило", body: "Если есть сомнение по аллергену, официант уточняет у кухни или администратора." },
      { title: "Ответ гостю", body: "Безопасность важнее скорости ответа. Нельзя обещать то, в чем сотрудник не уверен." },
    ],
    quiz: {
      question: "Что делать, если гость спрашивает про аллерген, а ты не уверен?",
      options: ["Ответить наугад", "Уточнить у кухни или администратора", "Сказать, что аллергенов нет"],
      answer: 1,
      explanation: "По стандарту нельзя угадывать состав, особенно если вопрос касается безопасности гостя.",
    },
  },
  {
    id: "drinks-pairing",
    order: 13,
    title: "Напитки и сочетания",
    subtitle: "Рекомендации к блюдам",
    type: "lesson",
    duration: "7 мин",
    xp: 12,
    stars: 0,
    source: "PDF: напитки и сочетания",
    goals: ["Знать напитки", "Подбирать сочетания", "Делать уместные рекомендации"],
    lessonCards: [
      { title: "Сочетания", body: "Рекомендация напитка должна подходить блюду, ситуации и настроению гостя." },
      { title: "Продажи", body: "Напитки помогают развивать сервис и средний чек без навязчивости." },
    ],
  },
  {
    id: "dish-presentation",
    order: 14,
    title: "Презентация блюд",
    subtitle: "Устная подача",
    type: "quiz",
    duration: "7 мин",
    xp: 15,
    stars: 1,
    passScore: 85,
    source: "PDF: устная презентация блюд",
    goals: ["Коротко описывать блюдо", "Связывать блюдо с запросом гостя", "Предлагать уверенно"],
    lessonCards: [
      { title: "Формула", body: "Название, ключевой вкус, особенность и кому подойдет блюдо." },
      { title: "Рекомендация", body: "Хорошая рекомендация звучит как помощь, а не как попытка продать любой ценой." },
    ],
    quiz: {
      question: "Какая рекомендация звучит лучше?",
      options: ["Берите это, все берут", "Если хотите легкое, советую салат с цитрусовой заправкой", "Не знаю, посмотрите меню"],
      answer: 1,
      explanation: "Рекомендация должна учитывать запрос гостя и объяснять пользу выбора.",
    },
  },
  {
    id: "menu-test",
    order: 15,
    title: "Тест по меню",
    subtitle: "Проходной балл 85%",
    type: "quiz",
    duration: "8 мин",
    xp: 20,
    stars: 2,
    passScore: 85,
    source: "PDF: тест в приложении",
    goals: ["Сдать тест выше 85%", "Получить значок", "Открыть стажировку в зале"],
    lessonCards: [
      { title: "Что проверяется", body: "Меню, состав, аллергены, напитки, сочетания, стоп-лист и популярные позиции." },
      { title: "Награда", body: "После успешного теста сотрудник получает +2 балла и значок «Знаю меню»." },
    ],
    quiz: {
      question: "Какой проходной балл у теста по меню?",
      options: ["70%", "80%", "85%"],
      answer: 2,
      explanation: "В PDF указан проходной балл 85%.",
    },
    achievementId: "menu-master",
  },
  {
    id: "mentor-shift-one",
    order: 16,
    title: "Смена с наставником 1",
    subtitle: "Встреча и размещение",
    type: "mentor",
    duration: "смена",
    xp: 18,
    stars: 1,
    source: "PDF: базовая стажировка 4-14 день",
    goals: ["Встретить гостя", "Разместить гостя", "Соблюдать стандарт общения"],
    lessonCards: [
      { title: "Реальный сервис", body: "Стажер работает в зале под контролем наставника и получает оценку после смены." },
      { title: "Контроль", body: "Наставник фиксирует внешний вид, дисциплину, коммуникацию, скорость и чистоту." },
    ],
    requiresMentor: true,
  },
  {
    id: "mentor-shift-two",
    order: 17,
    title: "Смена с наставником 2",
    subtitle: "Подача и уборка",
    type: "mentor",
    duration: "смена",
    xp: 18,
    stars: 1,
    source: "PDF: базовая стажировка",
    goals: ["Подать блюда", "Убрать стол", "Держать скорость без ошибок"],
    lessonCards: [
      { title: "Подача", body: "Стажер отрабатывает подачу блюд, работу с напитками и уборку стола." },
      { title: "Скорость", body: "Темп важен, но не должен ломать чистоту, коммуникацию и порядок действий." },
    ],
    requiresMentor: true,
  },
  {
    id: "pos-order",
    order: 18,
    title: "POS и расчет",
    subtitle: "Заказ, чек, оплата",
    type: "quiz",
    duration: "7 мин",
    xp: 18,
    stars: 1,
    passScore: 85,
    source: "PDF: работа с POS и расчет гостей",
    goals: ["Принять заказ", "Проверить позиции", "Провести расчет"],
    lessonCards: [
      { title: "Повтор заказа", body: "Перед отправкой в POS официант повторяет заказ гостю, чтобы избежать ошибок." },
      { title: "Расчет", body: "Расчет закрывает сервис: чек, способ оплаты, благодарность и приглашение вернуться." },
    ],
    quiz: {
      question: "Что нужно сделать перед отправкой заказа в POS?",
      options: ["Сразу закрыть чек", "Повторить заказ гостю", "Убрать стол"],
      answer: 1,
      explanation: "Повтор заказа снижает количество ошибок и конфликтов.",
    },
    achievementId: "pos-ready",
  },
  {
    id: "sales",
    order: 19,
    title: "Продажи и возражения",
    subtitle: "Upsell, cross-sell",
    type: "quiz",
    duration: "8 мин",
    xp: 20,
    stars: 2,
    passScore: 85,
    source: "PDF: допродажи и работа с возражениями",
    goals: ["Понять upsell", "Предлагать напитки и десерты", "Работать с возражениями"],
    lessonCards: [
      { title: "Upsell", body: "Официант предлагает более подходящую, расширенную или премиальную позицию." },
      { title: "Cross-sell", body: "К блюду можно предложить напиток, соус, гарнир или десерт, если это уместно." },
    ],
    quiz: {
      question: "Что такое upsell?",
      options: ["Предложение более подходящей или премиальной позиции", "Уборка стола", "Закрытие смены"],
      answer: 0,
      explanation: "Upsell помогает увеличить ценность заказа, если рекомендация уместна для гостя.",
    },
    achievementId: "seller",
  },
  {
    id: "final-exam",
    order: 20,
    title: "Допуск к работе",
    subtitle: "Теория + практика",
    type: "exam",
    duration: "10 мин",
    xp: 50,
    stars: 10,
    passScore: 85,
    source: "PDF: Этап 3, допуск к самостоятельной работе",
    goals: ["Сдать теорию выше 85%", "Получить практическое подтверждение", "Открыть статус официанта"],
    lessonCards: [
      { title: "Теория", body: "Меню, стандарты, сервис, санитария и продажи проверяются перед самостоятельной работой." },
      { title: "Практика", body: "Наставник подтверждает обслуживание стола, заказ, конфликт, продажу, подачу и работу с гостем." },
      { title: "Условия", body: "Нет грубых нарушений, практический экзамен пройден, наставник рекомендует сотрудника." },
    ],
    quiz: {
      question: "Что требуется для допуска к самостоятельной работе?",
      options: ["Только тест", "Тест выше 85%, практика и рекомендация наставника", "Только знание меню"],
      answer: 1,
      explanation: "В PDF допуск выдается при тесте выше 85%, пройденной практике и рекомендации наставника.",
    },
    achievementId: "waiter",
    requiresMentor: true,
  },
];

export const achievements: Achievement[] = [
  { id: "first-step", title: "Первый шаг", description: "Первый урок пройден", tone: "green" },
  { id: "appearance", title: "Стандарт формы", description: "Внешний вид изучен", tone: "ink" },
  { id: "service-standard", title: "Знаю сервис", description: "Основы обслуживания закрыты", tone: "blue" },
  { id: "menu-master", title: "Знаю меню", description: "Тест по меню сдан", tone: "gold" },
  { id: "perfect-test", title: "Без ошибок", description: "Тест пройден с первой попытки", tone: "ink" },
  { id: "team-player", title: "Командный игрок", description: "Наставник отметил практику", tone: "coral" },
  { id: "floor-ready", title: "Готов к залу", description: "Практика с подносом подтверждена", tone: "green" },
  { id: "pos-ready", title: "POS готов", description: "Заказ и расчет отработаны", tone: "blue" },
  { id: "seller", title: "Продажник", description: "Модуль продаж закрыт", tone: "gold" },
  { id: "waiter", title: "Официант", description: "Финальный допуск получен", tone: "blue" },
];

export const rewards: Reward[] = [
  { id: "pin", title: "Фирменный значок", description: "Для формы после первой главы", cost: 3, category: "Мерч" },
  { id: "dessert", title: "Кофе или десерт", description: "Награда после смены", cost: 5, category: "Еда" },
  { id: "certificate", title: "Сертификат стажера", description: "После базовой адаптации", cost: 8, category: "Развитие" },
  { id: "shirt", title: "Футболка команды", description: "Мерч для активных стажеров", cost: 12, category: "Мерч" },
  { id: "shift", title: "Выбор смены", description: "Один приоритет в расписании", cost: 16, category: "Смена" },
  { id: "training", title: "Закрытое обучение", description: "Доступ к развитию продаж", cost: 20, category: "Развитие" },
  { id: "hoodie", title: "Худи", description: "Премиальная награда", cost: 25, category: "Мерч" },
];

export const mentorSkills: MentorSkill[] = [
  { id: "appearance", title: "Внешний вид", description: "Форма, аккуратность, готовность к смене" },
  { id: "discipline", title: "Дисциплина", description: "Пунктуальность, правила, ответственность" },
  { id: "communication", title: "Коммуникация", description: "Тон, фразы, работа с гостем" },
  { id: "menu", title: "Знание меню", description: "Состав, аллергены, рекомендации" },
  { id: "sales", title: "Продажи", description: "Upsell, рекомендации, работа с возражениями" },
  { id: "speed", title: "Скорость", description: "Темп работы без потери качества" },
  { id: "cleanliness", title: "Чистота", description: "Стол, станция, сервировка" },
];

export const dailyControls: DailyControl[] = [
  { id: "appearance", title: "Внешний вид", description: "Форма и аккуратность", targetScore: 4 },
  { id: "discipline", title: "Дисциплина", description: "Без опозданий и нарушений", targetScore: 4 },
  { id: "communication", title: "Коммуникация", description: "Правильный тон с гостем", targetScore: 4 },
  { id: "menu", title: "Знание меню", description: "Состав, аллергены, рекомендации", targetScore: 4 },
  { id: "sales", title: "Продажи", description: "Десерты, напитки, upsell", targetScore: 4 },
  { id: "speed", title: "Скорость", description: "Темп без потери качества", targetScore: 4 },
  { id: "cleanliness", title: "Чистота", description: "Стол, станция, зал", targetScore: 4 },
];

export const bonusRules: BonusRule[] = [
  { action: "Успешно закрытая смена", reward: "+1 балл опыта и рейтинг", type: "xp" },
  { action: "Нет опозданий 7 дней", reward: "Серия бонусов", type: "stars" },
  { action: "Лучший тест недели", reward: "Дополнительные звезды", type: "stars" },
  { action: "Лучшая продажа дня", reward: "Повышенный рейтинг", type: "rating" },
  { action: "Отсутствие жалоб", reward: "Бонус к профилю", type: "rating" },
  { action: "Помощь команде", reward: "Лидерские баллы", type: "stars" },
  { action: "Успешный upsell", reward: "Звезды и рейтинг", type: "stars" },
];

export const penaltyRules: PenaltyRule[] = [
  { reason: "Опоздание", penalty: "снимаются баллы серии" },
  { reason: "Нарушение формы", penalty: "минус к ежедневной оценке" },
  { reason: "Жалоба гостя", penalty: "снижение рейтинга" },
  { reason: "Несоблюдение стандартов", penalty: "повторная практика" },
  { reason: "Провал теста", penalty: "урок остается закрытым" },
  { reason: "Конфликтность", penalty: "допуск блокируется до разбора" },
];

export const admissionRequirements: AdmissionRequirement[] = [
  { id: "theory", title: "Тест выше 85%", description: "Меню, стандарты, сервис, санитария и продажи" },
  { id: "practice", title: "Практика пройдена", description: "Обслуживание стола, заказ, подача и работа с гостем" },
  { id: "clean-record", title: "Нет грубых нарушений", description: "Нет жалоб, конфликтов и критичных ошибок" },
  { id: "mentor", title: "Рекомендация наставника", description: "Наставник подтверждает готовность к самостоятельной работе" },
];

export const traineeSummaries: TraineeSummary[] = [
  {
    id: "alina",
    name: "Алина С.",
    role: "Стажер",
    status: "Основной путь",
    progressLabel: "Активная карточка",
    mentor: "Наставник смены",
  },
  {
    id: "maksim",
    name: "Максим Р.",
    role: "Стажер",
    status: "День 2",
    progressLabel: "Нужен чек-лист сервиса",
    mentor: "Наставник смены",
  },
  {
    id: "dina",
    name: "Дина К.",
    role: "Помощник официанта",
    status: "4-14 день",
    progressLabel: "Смена с наставником",
    mentor: "Старший официант",
  },
];

export const shiftJournal: ShiftJournalEntry[] = [
  {
    id: "shift-day-4",
    day: "День 4",
    title: "Смена с наставником 1",
    focus: "Встреча гостей, размещение, первый контакт и дисциплина.",
    missionId: "mentor-shift-one",
  },
  {
    id: "shift-day-6",
    day: "День 6",
    title: "Подача и уборка",
    focus: "Подача блюд, работа с напитками, скорость и чистота станции.",
    missionId: "mentor-shift-two",
  },
  {
    id: "shift-day-8",
    day: "День 8",
    title: "POS и заказ",
    focus: "Повтор заказа, корректное внесение позиций и расчет гостя.",
    missionId: "pos-order",
  },
  {
    id: "shift-day-10",
    day: "День 10",
    title: "Продажи",
    focus: "Рекомендации, upsell, десерты, напитки и работа с возражениями.",
    missionId: "sales",
  },
  {
    id: "shift-day-14",
    day: "День 14",
    title: "Преддопуск",
    focus: "Полный цикл обслуживания перед финальным экзаменом.",
    missionId: "final-exam",
  },
];

export const practicalExamItems: PracticalExamItem[] = [
  {
    id: "table-service",
    title: "Обслуживание стола",
    description: "Полный цикл: приветствие, меню, заказ, контроль стола и прощание.",
  },
  {
    id: "order-taking",
    title: "Принятие заказа",
    description: "Повтор заказа, уточнение деталей и корректная передача в POS.",
  },
  {
    id: "conflict-case",
    title: "Конфликтная ситуация",
    description: "Спокойная реакция, извинение, уточнение проблемы и подключение старшего.",
  },
  {
    id: "sale-scenario",
    title: "Сценарий продажи",
    description: "Уместная рекомендация напитка, десерта или премиальной позиции.",
  },
  {
    id: "serving",
    title: "Подача блюд",
    description: "Аккуратность, темп, правильная постановка и проверка стола.",
  },
  {
    id: "guest-work",
    title: "Работа с гостем",
    description: "Тон общения, внимание к запросам и уверенное завершение сервиса.",
  },
];

export const defaultTrainingState: TrainingState = {
  completedMissionIds: [],
  xp: 0,
  stars: 0,
  unlockedAchievementIds: [],
  reservedRewardIds: [],
  mentorApprovedMissionIds: [],
  mentorScores: {
    appearance: 4,
    discipline: 4,
    communication: 5,
    menu: 4,
    sales: 3,
    speed: 4,
    cleanliness: 5,
  },
  mentorComment: "Стажер уверенно общается с гостем. Усилить продажи и работу с POS до финального допуска.",
  shiftEntryStatuses: {
    "shift-day-4": "pending",
    "shift-day-6": "pending",
    "shift-day-8": "pending",
    "shift-day-10": "pending",
    "shift-day-14": "pending",
  },
  shiftEntryComments: {
    "shift-day-4": "Проверить приветствие и уверенность при размещении гостей.",
    "shift-day-6": "Закрепить подачу и уборку стола без потери темпа.",
    "shift-day-8": "Отработать повтор заказа перед отправкой в POS.",
    "shift-day-10": "Добавить мягкие рекомендации по десертам и напиткам.",
    "shift-day-14": "Перед допуском пройти полный цикл обслуживания.",
  },
  practicalExamChecks: {
    "table-service": false,
    "order-taking": false,
    "conflict-case": false,
    "sale-scenario": false,
    serving: false,
    "guest-work": false,
  },
  missionBlockOrders: {},
  missionContentDrafts: {},
  finalApproved: false,
};
